from pathlib import Path
p=Path('index.html');s=p.read_text(encoding='utf-8-sig').replace('على ذوقك.<br><em>وبكل حب.</em>','مزاجك اليوم،<br><em>شنو يليق ليه؟</em>').replace('اختار مشروبك وخلي الباقي علينا','قهوة، ماتشا ولا شي حاجة منعشة؟<br>اختار اللي على خاطرك.').replace('أهلاً بك في مول الدكة','مرحبا بيك فمول الدكة').replace('لحظة حلوة، رشفة مميزة','رشفة تبدّل المود').replace('اكتشف مشروبك المفضل','شي حاجة على ذوقك').replace('قائمة <em>المشروبات</em>','اختار <em>مشروبك</em>').replace('بحث عن مشروب أو نكهة...','شنو بغيتي تشرب؟').replace('<link rel="stylesheet"','<link rel="preload" href="assets/fonts/Tajawal-Regular.ttf" as="font" type="font/ttf" crossorigin><link rel="stylesheet"');p.write_text(s,encoding='utf8')
p=Path('css/style.css');s=p.read_text(encoding='utf-8-sig');s=s.replace('font-family:Tahoma,Arial,sans-serif','font-family:"Tajawal",Arial,sans-serif');s='''@font-face{font-family:Tajawal;src:url('../assets/fonts/Tajawal-Regular.ttf') format('truetype');font-weight:400;font-display:swap}
@font-face{font-family:Tajawal;src:url('../assets/fonts/Tajawal-Bold.ttf') format('truetype');font-weight:700 900;font-display:swap}
'''+s
s+='''
/* Refined typography and compact QR browsing on phones. */
body{line-height:1.55}.brand strong{font-weight:700;line-height:1.2}.eyebrow{letter-spacing:0}.welcome h1{font-weight:700;font-size:clamp(34px,4.4vw,58px);line-height:1.2;letter-spacing:-1px}.welcome p{line-height:1.8}.card h3,.detail-copy h2{font-family:Arial,sans-serif}.card h3{font-weight:600}.card-category,.card-action{font-size:12px}.chip{font-size:15px}.bottom-nav svg{width:23px;height:23px;fill:none;stroke:currentColor;stroke-width:1.6;stroke-linecap:round;stroke-linejoin:round}.bottom-nav a,.bottom-nav button{font-size:12px}.muted{font-size:13px}.poster-link{font-size:13px}
@media(max-width:600px){
html{scroll-padding-top:130px}.header{padding:12px 16px;min-height:76px}.brand{gap:9px}.brand img{width:50px;height:50px}.brand strong{font-size:24px}.brand small{font-family:Arial,sans-serif;font-size:8px;letter-spacing:2px;margin-top:4px}.header-note{font-size:12px}.header-note span{display:none}main{padding:0 14px}.welcome{grid-template-columns:minmax(0,1.25fr) minmax(0,1fr);gap:10px;padding:16px 0 12px}.welcome-copy{min-width:0}.welcome .eyebrow{font-size:12px}.welcome h1{font-size:clamp(25px,7.2vw,32px);line-height:1.22;letter-spacing:-.4px;margin:10px 0 7px}.welcome p{font-size:13px;line-height:1.5;margin:6px 0}.explore{min-height:44px;font-size:13px;padding:9px 15px;gap:16px}.welcome-image{height:184px;border-radius:48px 12px 12px 12px}.welcome-image img{object-position:center 42%}.image-caption{font-size:10px;padding:6px 9px;left:7px;bottom:8px}.intro-line{display:none}.toolbar{padding:8px 0;background:var(--bg);border-bottom:1px solid var(--line)}.search-wrap{min-height:48px;border-radius:13px}input{font-size:16px;padding:12px 0}.categories{gap:8px;padding:10px 0 2px}.chip{font-size:14px;min-height:44px;padding:8px 16px}.chip small{font-size:11px}.section-heading{margin:18px 0 14px;align-items:end}.section-heading .eyebrow{display:none}.section-heading h2{font-size:26px;margin:0;line-height:1.2}.section-heading #count{font-size:12px}.grid{gap:14px 10px}.card-visual{aspect-ratio:1/1.05}.card-info{padding:11px}.card h3{font-size:14px;line-height:1.4;min-height:40px;margin-bottom:5px}.card-category{font-size:12px;margin-bottom:6px}.card-action{font-size:12px}.card-action b{width:30px;height:30px}.bottom-nav{bottom:0;width:100%;border-radius:18px 18px 0 0;padding:7px 12px max(7px,env(safe-area-inset-bottom));background:#fffdf9;border:0;border-top:1px solid var(--line);box-shadow:0 -4px 20px #54230d08;backdrop-filter:none}.bottom-nav a,.bottom-nav button{font-size:12px;min-height:48px;gap:3px;flex:1}.detail-visual{height:230px}.detail-copy{padding:20px 20px max(24px,env(safe-area-inset-bottom))}.detail-copy h2{font-size:24px}.detail-copy h3{font-size:17px}.ingredients li{font-size:14px}.quantity-row{font-size:16px}.order{font-size:16px;min-height:52px}.order-status{font-size:14px}.favorite{font-size:14px}.empty h3{font-size:21px}.empty p{font-size:15px}
}
@media(max-width:340px){.welcome h1{font-size:25px}.welcome p{font-size:12px}.welcome-image{height:180px}.image-caption{font-size:9px}.card-info{padding:10px 8px}.card h3{font-size:13px}.chip small{display:inline}.header-note{display:none}}
''';p.write_text(s,encoding='utf8')
# Replace inconsistent font glyphs with small local vector icons.
p=Path('index.html');s=p.read_text(encoding='utf8');icons={'⌂':'<path d="m3 10 9-7 9 7v10H3z"/><path d="M9 20v-7h6v7"/>','☷':'<path d="M9 5h12M9 12h12M9 19h12"/><path d="M3 5h1M3 12h1M3 19h1"/>','⌕':'<circle cx="10.5" cy="10.5" r="7"/><path d="m16 16 5 5"/>','♡':'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8z"/>'}
for glyph,paths in icons.items():s=s.replace('<span aria-hidden="true">'+glyph+'</span>','<svg aria-hidden="true" viewBox="0 0 24 24">'+paths+'</svg>')
p.write_text(s,encoding='utf8')
